using System.Linq;
using System.Windows.Forms;
using TheTechIdea.Beep.Winform.Controls;
using TheTechIdea.Beep.Winform.Controls.Integrated.Blocks.Models;

namespace TheTechIdea.Beep.Winform.Controls.Integrated.Blocks
{
    public partial class BeepBlock
    {
        private void RebuildRecordLayoutFromDefinition()
        {
            // When controls were generated by the IDE extension into Designer.cs we do not
            // create our own internal editor rows — the designer-generated controls are
            // registered via BindControl() and refreshed by RefreshGeneratedFieldControls().
            if ((EffectiveDefinition?.PresentationMode ?? BeepBlockPresentationMode.Record)
                    == BeepBlockPresentationMode.DesignerGenerated)
                return;

            if (_recordHostPanel == null)
            {
                return;
            }

            CaptureQueryCriteriaFromEditors();
            _recordHostPanel.SuspendLayout();
            _recordHostPanel.Controls.Clear();
            _fieldEditors.Clear();
            _fieldRows.Clear();
            _fieldLabels.Clear();
            _fieldStateLabels.Clear();
            _queryOperatorEditors.Clear();
            _queryEditorGroups.Clear();

            var definition = EffectiveDefinition;
            if (definition?.Fields == null || definition.Fields.Count == 0)
            {
                _recordHostPanel.ResumeLayout(false);
                return;
            }

            var fields = GetRenderableFields(definition).ToList();
            if (ViewState.IsQueryMode && fields.Count == 0)
            {
                _recordHostPanel.Controls.Add(new BeepLabel
                {
                    Width = System.Math.Max(200, _recordHostPanel.ClientSize.Width - 24),
                    Height = 36,
                    Text = "FormsManager has not exposed any queryable items for this block.",
                    UseThemeColors = true,
                    Multiline = true,
                    WordWrap = true
                });
                _recordHostPanel.ResumeLayout(false);
                return;
            }

            foreach (var field in fields)
            {
                BeepPanel rowPanel = new()
                {
                    Width = System.Math.Max(200, _recordHostPanel.ClientSize.Width - 24),
                    Height = ViewState.IsQueryMode ? 64 : 56,
                    Margin = new Padding(0, 0, 0, 8),
                    ShowTitle = false,
                    ShowTitleLine = false,
                    UseThemeColors = true
                };

                var label = new BeepLabel
                {
                    Dock = DockStyle.Fill,
                    Text = string.IsNullOrWhiteSpace(field.Label) ? field.FieldName : field.Label,
                    UseThemeColors = true
                };

                var stateLabel = new BeepLabel
                {
                    Dock = DockStyle.Right,
                    Width = 92,
                    TextAlign = ContentAlignment.MiddleCenter,
                    Padding = new Padding(6, 0, 6, 0),
                    UseThemeColors = false,
                    Visible = false
                };

                var headerHost = new Panel
                {
                    Dock = DockStyle.Top,
                    Height = 20,
                    Margin = new Padding(0),
                    Padding = new Padding(0)
                };
                headerHost.Controls.Add(label);
                headerHost.Controls.Add(stateLabel);

                Control editor;
                if (ViewState.IsQueryMode)
                {
                    var queryOperatorEditor = CreateQueryOperatorEditor(field);
                    var queryEditorGroup = CreateQueryEditorGroup(field);
                    editor = queryEditorGroup.PrimaryEditor;
                    editor.Height = 30;

                    var contentHost = new TableLayoutPanel
                    {
                        Dock = DockStyle.Fill,
                        ColumnCount = 3,
                        RowCount = 1,
                        Margin = new Padding(0),
                        Padding = new Padding(0)
                    };
                    contentHost.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 128f));
                    contentHost.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100f));
                    contentHost.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 74f));

                    var clearFieldButton = new BeepButton
                    {
                        Dock = DockStyle.Fill,
                        Text = "Reset",
                        Theme = Theme,
                        ShowShadow = false,
                        Margin = new Padding(8, 0, 0, 0)
                    };
                    clearFieldButton.Click += (_, _) => ClearQueryCriterion(field.FieldName);

                    queryOperatorEditor.Margin = new Padding(0, 0, 8, 0);
                    queryEditorGroup.Host.Margin = new Padding(0);

                    contentHost.Controls.Add(queryOperatorEditor, 0, 0);
                    contentHost.Controls.Add(queryEditorGroup.Host, 1, 0);
                    contentHost.Controls.Add(clearFieldButton, 2, 0);

                    rowPanel.Controls.Add(contentHost);
                    rowPanel.Controls.Add(headerHost);
                    _recordHostPanel.Controls.Add(rowPanel);

                    _fieldEditors[field.FieldName] = editor;
                    _fieldRows[field.FieldName] = rowPanel;
                    _fieldLabels[field.FieldName] = label;
                    _fieldStateLabels[field.FieldName] = stateLabel;
                    _queryOperatorEditors[field.FieldName] = queryOperatorEditor;
                    _queryEditorGroups[field.FieldName] = queryEditorGroup;
                    continue;
                }

                var presenter = PresenterRegistry.Resolve(field);
                if (presenter == null)
                {
                    continue;
                }

                editor = presenter.CreateEditor(field);
                presenter.ApplyMetadata(editor, field);
                BindEditorToCurrentRecord(editor, field);

                Control editorHost = CreateRecordEditorHost(editor, field);
                rowPanel.Controls.Add(editorHost);
                rowPanel.Controls.Add(headerHost);
                _recordHostPanel.Controls.Add(rowPanel);
                _fieldEditors[field.FieldName] = editor;
                _fieldRows[field.FieldName] = rowPanel;
                _fieldLabels[field.FieldName] = label;
                _fieldStateLabels[field.FieldName] = stateLabel;
            }

            _recordHostPanel.ResumeLayout(false);
        }
    }
}