

using TheTechIdea.Beep.Vis.Modules;
using TheTechIdea.Beep.Winform.Controls;
using TheTechIdea.Beep.Winform.Controls.Models;
using TheTechIdea.Beep.Winform.Controls.TextFields;

namespace TheTechIdea.Beep.Winform.Default.Views.Configuration
{
    partial class uc_FilterForm
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            BeepRowConfig beepRowConfig1 = new BeepRowConfig();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(uc_FilterForm));
            BeepColumnConfig beepColumnConfig1 = new BeepColumnConfig();
            BeepColumnConfig beepColumnConfig2 = new BeepColumnConfig();
            BeepColumnConfig beepColumnConfig3 = new BeepColumnConfig();
            beepLabel1 = new BeepLabel();
            beepTextBox1 = new BeepTextBox();
            beepSimpleGrid1 = new TheTechIdea.Beep.Winform.Controls.GridX.BeepGridPro();
            SuspendLayout();
            // 
            // uc_FilterForm
            // 
            Controls.Add(beepSimpleGrid1);
            Controls.Add(beepTextBox1);
            Controls.Add(beepLabel1);
            // 
            // beepLabel1
            // 
            beepLabel1.AnimationDuration = 500;
            beepLabel1.AnimationType = DisplayAnimationType.None;
            beepLabel1.ApplyThemeOnImage = false;
            beepLabel1.ApplyThemeToChilds = false;
            beepLabel1.AutoDrawHitListComponents = true;
            beepLabel1.BackColor = Color.White;
            beepLabel1.BadgeBackColor = Color.Red;
            beepLabel1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepLabel1.BadgeForeColor = Color.White;
            beepLabel1.BadgeShape = BadgeShape.Circle;
            beepLabel1.BadgeText = "";
            beepLabel1.BlockID = null;
            beepLabel1.BorderColor = Color.LightGray;
            beepLabel1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepLabel1.BorderRadius = 3;
            beepLabel1.BorderStyle = BorderStyle.FixedSingle;
            beepLabel1.BorderThickness = 1;
            beepLabel1.BottomoffsetForDrawingRect = 0;
            beepLabel1.BoundProperty = "Text";
            beepLabel1.CanBeFocused = true;
            beepLabel1.CanBeHovered = false;
            beepLabel1.CanBePressed = true;
            beepLabel1.Category = Utilities.DbFieldCategory.String;
            beepLabel1.ComponentName = "beepLabel1";
            beepLabel1.DataSourceProperty = null;
            beepLabel1.DisabledBackColor = Color.LightGray;
            beepLabel1.DisabledBorderColor = Color.Empty;
            beepLabel1.DisabledForeColor = Color.Gray;
            //beepLabel1.DisableDpiAndScaling = false;
            beepLabel1.DrawingRect = new Rectangle(1, 1, 220, 54);
            beepLabel1.Easing = EasingType.Linear;
            beepLabel1.EnableHighQualityRendering = true;            beepLabel1.EnableRippleEffect = false;
            beepLabel1.EnableSplashEffect = false;
            beepLabel1.ErrorColor = Color.FromArgb(176, 0, 32);
            beepLabel1.ErrorText = "";
            beepLabel1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepLabel1.FieldID = null;
            beepLabel1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepLabel1.FloatingLabel = string.Empty;
            beepLabel1.FocusBackColor = Color.White;
            beepLabel1.FocusBorderColor = Color.Gray;
            beepLabel1.FocusForeColor = Color.Black;
            beepLabel1.FocusIndicatorColor = Color.Blue;
            beepLabel1.Font = new Font("Arial", 12F);
            beepLabel1.ForeColor = Color.FromArgb(33, 33, 33);
            beepLabel1.Form = null;
            beepLabel1.GlassmorphismBlur = 10F;
            beepLabel1.GlassmorphismOpacity = 0.1F;
            beepLabel1.GradientAngle = 0F;
            beepLabel1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepLabel1.GradientEndColor = Color.Gray;
            beepLabel1.GradientStartColor = Color.Gray;
            beepLabel1.GridMode = false;
            beepLabel1.GuidID = "b6a16bce-4329-420a-bcbf-68edc27af5cc";
            beepLabel1.HasError = false;
            beepLabel1.HeaderSubheaderSpacing = 2;
            beepLabel1.HelperText = "";
            beepLabel1.HideText = false;
            beepLabel1.HitAreaEventOn = false;
            beepLabel1.HitTestControl = null;
            beepLabel1.HoverBackColor = Color.FromArgb(230, 240, 255);
            beepLabel1.HoverBorderColor = Color.Gray;
            beepLabel1.HoveredBackcolor = Color.FromArgb(230, 240, 255);
            beepLabel1.HoverForeColor = Color.FromArgb(33, 150, 243);
            beepLabel1.IconSize = 20;
            beepLabel1.Id = -1;
            beepLabel1.ImageAlign = ContentAlignment.MiddleLeft;
            beepLabel1.ImagePath = "C:\\Users\\f_ald\\OneDrive\\docs_pic\\IMG_1074.jpg";
            beepLabel1.InactiveBorderColor = Color.Gray;
            beepLabel1.InnerShape = null;
            beepLabel1.IsAcceptButton = false;
            beepLabel1.IsBorderAffectedByTheme = true;
            beepLabel1.IsCancelButton = false;
            beepLabel1.IsChild = false;
            beepLabel1.IsCustomeBorder = false;
            beepLabel1.IsDefault = false;
            beepLabel1.IsDeleted = false;
            beepLabel1.IsDirty = false;
            beepLabel1.IsEditable = false;
            beepLabel1.IsFocused = false;
          
            beepLabel1.IsFrameless = false;
            beepLabel1.IsHovered = false;
           
            beepLabel1.IsNew = false;
            beepLabel1.IsPressed = false;
           
            beepLabel1.IsReadOnly = false;
            beepLabel1.IsRequired = false;
            beepLabel1.IsRounded = true;
            beepLabel1.IsRoundedAffectedByTheme = true;
            beepLabel1.IsSelected = false;
          
            beepLabel1.IsSelectedOptionOn = true;
            beepLabel1.IsShadowAffectedByTheme = true;
            beepLabel1.IsValid = true;
            beepLabel1.IsVisible = true;
            beepLabel1.Items = (List<object>)resources.GetObject("beepLabel1.Items");
            beepLabel1.LabelBackColor = Color.Empty;
           
            beepLabel1.LabelText = "";
            beepLabel1.LeadingIconPath = "";
            beepLabel1.LeadingImagePath = "";
            beepLabel1.LeftoffsetForDrawingRect = 0;
            beepLabel1.LinkedProperty = null;
            beepLabel1.Location = new Point(414, 17);
            beepLabel1.Margin = new Padding(0);
          
            beepLabel1.MaxHitListDrawPerFrame = 0;
            beepLabel1.MaxImageSize = new Size(48, 48);
            beepLabel1.MinimumSize = new Size(182, 56);
            beepLabel1.ModernGradientType = ModernGradientType.Subtle;
            beepLabel1.Multiline = false;
            beepLabel1.Name = "beepLabel1";
            beepLabel1.OverrideFontSize = TypeStyleFontSize.None;
            beepLabel1.Padding = new Padding(1);
            beepLabel1.ParentBackColor = Color.Empty;
            beepLabel1.ParentControl = null;
            beepLabel1.PressedBackColor = Color.White;
            beepLabel1.PressedBorderColor = Color.Gray;
            beepLabel1.PressedForeColor = Color.Gray;
            beepLabel1.RadialCenter = (PointF)resources.GetObject("beepLabel1.RadialCenter");
            beepLabel1.RightoffsetForDrawingRect = 0;
            beepLabel1.SavedGuidID = null;
            beepLabel1.SavedID = null;
            beepLabel1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepLabel1.SelectedBackColor = Color.FromArgb(200, 220, 255);
            beepLabel1.SelectedBorderColor = Color.Empty;
            beepLabel1.SelectedForeColor = Color.FromArgb(33, 33, 33);
            beepLabel1.SelectedValue = null;
            beepLabel1.ShadowColor = Color.Black;
            beepLabel1.ShadowOffset = 0;
            beepLabel1.ShadowOpacity = 0.5F;
            beepLabel1.ShowAllBorders = false;
            beepLabel1.ShowBottomBorder = false;
            beepLabel1.ShowFocusIndicator = false;
            beepLabel1.ShowLeftBorder = false;
            beepLabel1.ShowRightBorder = false;
            beepLabel1.ShowShadow = false;
            beepLabel1.ShowTopBorder = false;
            beepLabel1.Size = new Size(222, 56);
            beepLabel1.SlideFrom = SlideDirection.Left;
            beepLabel1.StaticNotMoving = false;
            beepLabel1.SubHeaderFont = new Font("Arial", 10F);
            beepLabel1.SubHeaderForeColor = Color.FromArgb(83, 83, 83);
            beepLabel1.SubHeaderText = "I.T. Info. Specilaist";
            beepLabel1.TabIndex = 12;
           
            beepLabel1.TempBackColor = Color.Empty;
            beepLabel1.Text = "Fahad Aldhubaib";
            beepLabel1.TextAlign = ContentAlignment.MiddleLeft;
            beepLabel1.TextFont = new Font("Arial", 10F);
            beepLabel1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepLabel1.Theme = "DefaultType";
            beepLabel1.ToolTipText = "";
            beepLabel1.TopoffsetForDrawingRect = 0;
            beepLabel1.TrailingIconPath = "";
            beepLabel1.TrailingImagePath = "";
            beepLabel1.UseExternalBufferedGraphics = false;
            beepLabel1.UseGlassmorphism = false;
            beepLabel1.UseGradientBackground = false;
            beepLabel1.UseRichToolTip = true;
            beepLabel1.UseScaledFont = false;
            beepLabel1.UseThemeFont = true;
            // 
            // beepTextBox1
            // 
            beepTextBox1.AcceptsReturn = false;
            beepTextBox1.AcceptsTab = false;
            beepTextBox1.AnimationDuration = 500;
            beepTextBox1.AnimationType = DisplayAnimationType.None;
            beepTextBox1.ApplyThemeOnImage = false;
            beepTextBox1.ApplyThemeToChilds = false;
            beepTextBox1.AutoCompleteMode = AutoCompleteMode.None;
            beepTextBox1.AutoCompleteSource = AutoCompleteSource.None;
            beepTextBox1.AutoDrawHitListComponents = true;
            beepTextBox1.BackColor = Color.White;
            beepTextBox1.BadgeBackColor = Color.FromArgb(33, 150, 243);
            beepTextBox1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepTextBox1.BadgeForeColor = Color.White;
            beepTextBox1.BadgeShape = BadgeShape.Circle;
            beepTextBox1.BadgeText = "";
            beepTextBox1.BlockID = null;
            beepTextBox1.BorderColor = Color.FromArgb(200, 200, 200);
            beepTextBox1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepTextBox1.BorderRadius = 3;
            beepTextBox1.BorderStyle = BorderStyle.FixedSingle;
            beepTextBox1.BorderThickness = 1;
            beepTextBox1.BottomoffsetForDrawingRect = 0;
            beepTextBox1.BoundProperty = "Text";
            beepTextBox1.CanBeFocused = true;
            beepTextBox1.CanBeHovered = false;
            beepTextBox1.CanBePressed = true;
            beepTextBox1.Category = Utilities.DbFieldCategory.String;
            beepTextBox1.ComponentName = "beepTextBox1";
            beepTextBox1.CustomMask = "";
            beepTextBox1.DataSourceProperty = null;
            beepTextBox1.DateFormat = "MM/dd/yyyy HH:mm:ss";
            beepTextBox1.DateTimeFormat = "MM/dd/yyyy HH:mm:ss";
            beepTextBox1.DisabledBackColor = Color.FromArgb(200, 200, 200);
            beepTextBox1.DisabledBorderColor = Color.LightGray;
            beepTextBox1.DisabledForeColor = Color.Gray;
            //beepTextBox1.DisableDpiAndScaling = false;
            beepTextBox1.DrawingRect = new Rectangle(4, 4, 192, 20);
            beepTextBox1.Easing = EasingType.Linear;
            beepTextBox1.EnableHighQualityRendering = true;            beepTextBox1.EnableRippleEffect = false;
            beepTextBox1.EnableSplashEffect = false;
            beepTextBox1.ErrorColor = Color.FromArgb(176, 0, 32);
            beepTextBox1.ErrorText = "";
            beepTextBox1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepTextBox1.FieldID = null;
            beepTextBox1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepTextBox1.FloatingLabel = string.Empty;
            beepTextBox1.FocusBackColor = Color.White;
            beepTextBox1.FocusBorderColor = Color.FromArgb(0, 120, 215);
            beepTextBox1.FocusForeColor = Color.Black;
            beepTextBox1.FocusIndicatorColor = Color.Blue;
            beepTextBox1.Font = new Font("Garamond", 11F);
            beepTextBox1.ForeColor = Color.Black;
            beepTextBox1.Form = null;
            beepTextBox1.GlassmorphismBlur = 10F;
            beepTextBox1.GlassmorphismOpacity = 0.1F;
            beepTextBox1.GradientAngle = 0F;
            beepTextBox1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepTextBox1.GradientEndColor = Color.FromArgb(230, 230, 230);
            beepTextBox1.GradientStartColor = Color.FromArgb(255, 255, 255);
            beepTextBox1.GridMode = false;
            beepTextBox1.GuidID = "76d52a8f-ce6c-40ce-933c-c57583353d9e";
            beepTextBox1.HasError = false;
            beepTextBox1.HelperText = "";
            beepTextBox1.HideSelection = true;
            beepTextBox1.HitAreaEventOn = false;
            beepTextBox1.HitTestControl = null;
            beepTextBox1.HoverBackColor = Color.WhiteSmoke;
            beepTextBox1.HoverBorderColor = Color.Gray;
            beepTextBox1.HoveredBackcolor = Color.WhiteSmoke;
            beepTextBox1.HoverForeColor = Color.Black;
            beepTextBox1.IconSize = 20;
            beepTextBox1.Id = -1;
            beepTextBox1.ImageAlign = ContentAlignment.MiddleLeft;
            beepTextBox1.ImagePath = "";
            beepTextBox1.InactiveBorderColor = Color.Gray;
            beepTextBox1.InnerShape = null;
            beepTextBox1.IsAcceptButton = false;
            beepTextBox1.IsBorderAffectedByTheme = false;
            beepTextBox1.IsCancelButton = false;
            beepTextBox1.IsChild = false;
            beepTextBox1.IsCustomeBorder = false;
            beepTextBox1.IsDefault = false;
            beepTextBox1.IsDeleted = false;
            beepTextBox1.IsDirty = false;
            beepTextBox1.IsEditable = false;
            beepTextBox1.IsFocused = false;
          
            beepTextBox1.IsFrameless = false;
            beepTextBox1.IsHovered = false;
          
            beepTextBox1.IsNew = false;
            beepTextBox1.IsPressed = false;
          
            beepTextBox1.IsReadOnly = false;
            beepTextBox1.IsRequired = false;
            beepTextBox1.IsRounded = true;
            beepTextBox1.IsRoundedAffectedByTheme = true;
            beepTextBox1.IsSelected = false;
           
            beepTextBox1.IsSelectedOptionOn = false;
            beepTextBox1.IsShadowAffectedByTheme = false;
            beepTextBox1.IsValid = true;
            beepTextBox1.IsVisible = true;
            beepTextBox1.Items = (List<object>)resources.GetObject("beepTextBox1.Items");
            beepTextBox1.LabelText = "";
            beepTextBox1.LeadingIconPath = "";
            beepTextBox1.LeadingImagePath = "";
            beepTextBox1.LeftoffsetForDrawingRect = 0;
            beepTextBox1.LineNumberBackColor = Color.FromArgb(248, 248, 248);
            beepTextBox1.LineNumberFont = new Font("Arial", 10F);
            beepTextBox1.LineNumberForeColor = Color.Gray;
            beepTextBox1.LinkedProperty = null;
            beepTextBox1.Location = new Point(90, 95);
          
            beepTextBox1.MaxHitListDrawPerFrame = 0;
            beepTextBox1.MaxImageSize = new Size(16, 16);
            beepTextBox1.MinimumSize = new Size(0, 28);
            beepTextBox1.ModernGradientType = ModernGradientType.Subtle;
            beepTextBox1.Modified = false;
            beepTextBox1.Multiline = false;
            beepTextBox1.Name = "beepTextBox1";
            beepTextBox1.OnlyCharacters = false;
            beepTextBox1.OnlyDigits = false;
            beepTextBox1.OverrideFontSize = TypeStyleFontSize.None;
            beepTextBox1.Padding = new Padding(3);
            beepTextBox1.ParentBackColor = Color.Empty;
            beepTextBox1.ParentControl = null;
            beepTextBox1.PasswordChar = '\0';
            beepTextBox1.PlaceholderText = "sdsdsd";
            beepTextBox1.PlaceholderTextColor = Color.Gray;
            beepTextBox1.PressedBackColor = Color.White;
            beepTextBox1.PressedBorderColor = Color.Gray;
            beepTextBox1.PressedForeColor = Color.Gray;
            beepTextBox1.RadialCenter = (PointF)resources.GetObject("beepTextBox1.RadialCenter");
            beepTextBox1.ReadOnly = false;
            beepTextBox1.RightoffsetForDrawingRect = 0;
            beepTextBox1.SavedGuidID = null;
            beepTextBox1.SavedID = null;
            beepTextBox1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepTextBox1.ScrollBars = ScrollBars.None;
            beepTextBox1.SelectedBackColor = Color.White;
            beepTextBox1.SelectedBorderColor = Color.Empty;
            beepTextBox1.SelectedForeColor = Color.Black;
            beepTextBox1.SelectedValue = null;
            beepTextBox1.SelectionBackColor = SystemColors.Highlight;
            beepTextBox1.SelectionLength = 0;
            beepTextBox1.SelectionStart = 0;
            beepTextBox1.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            beepTextBox1.ShadowOffset = 0;
            beepTextBox1.ShadowOpacity = 0.5F;
            beepTextBox1.ShowAllBorders = true;
            beepTextBox1.ShowBottomBorder = true;
            beepTextBox1.ShowFocusIndicator = false;
            beepTextBox1.ShowHorizontalScrollBar = false;
            beepTextBox1.ShowLeftBorder = true;
            beepTextBox1.ShowRightBorder = true;
            beepTextBox1.ShowScrollbars = false;
            beepTextBox1.ShowShadow = false;
            beepTextBox1.ShowTopBorder = true;
            beepTextBox1.ShowVerticalScrollBar = false;
            beepTextBox1.Size = new Size(200, 28);
            beepTextBox1.SlideFrom = SlideDirection.Left;
            beepTextBox1.StaticNotMoving = false;
            beepTextBox1.TabIndex = 15;
         
            beepTextBox1.TextAlignment = HorizontalAlignment.Left;
            beepTextBox1.TextFont = new Font("Arial", 10F);
            beepTextBox1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepTextBox1.Theme = "DefaultType";
            beepTextBox1.TimeFormat = "HH:mm:ss";
            beepTextBox1.ToolTipText = "";
            beepTextBox1.TopoffsetForDrawingRect = 0;
            beepTextBox1.TrailingIconPath = "";
            beepTextBox1.TrailingImagePath = "";
            beepTextBox1.UseExternalBufferedGraphics = false;
            beepTextBox1.UseGlassmorphism = false;
            beepTextBox1.UseGradientBackground = false;
            beepTextBox1.UseRichToolTip = true;
            beepTextBox1.UseSystemPasswordChar = false;
            beepTextBox1.UseThemeFont = true;
            beepTextBox1.WordWrap = true;
            // 
            // beepSimpleGrid1
            // 
            beepRowConfig1.DisplayIndex = -1;
            beepRowConfig1.Height = 25;
            beepRowConfig1.Id = "b6f43eaf-ec63-4064-9a89-0f6b89860bf2";
            beepRowConfig1.IsAggregation = true;
            beepRowConfig1.IsDataLoaded = false;
            beepRowConfig1.IsDeleted = false;
            beepRowConfig1.IsDirty = false;
            beepRowConfig1.IsEditable = false;
            beepRowConfig1.IsNew = false;
            beepRowConfig1.IsReadOnly = false;
            beepRowConfig1.IsSelected = false;
            beepRowConfig1.IsVisible = true;
            beepRowConfig1.OldDisplayIndex = 0;
            beepRowConfig1.RowCheckRect = new Rectangle(0, 0, 0, 0);
            beepRowConfig1.RowData = null;
            beepRowConfig1.RowIndex = 1;
            beepRowConfig1.UpperX = 0;
            beepRowConfig1.UpperY = 0;
            beepRowConfig1.Width = 100;
            beepSimpleGrid1.AnimationDuration = 500;
            beepSimpleGrid1.AnimationType = DisplayAnimationType.None;
            beepSimpleGrid1.ApplyThemeToChilds = false;
            beepSimpleGrid1.AutoDrawHitListComponents = true;
            beepSimpleGrid1.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            beepSimpleGrid1.BackColor = Color.White;
            beepSimpleGrid1.BadgeBackColor = Color.Red;
            beepSimpleGrid1.BadgeFont = new Font("Arial", 8F, FontStyle.Bold);
            beepSimpleGrid1.BadgeForeColor = Color.White;
            beepSimpleGrid1.BadgeShape = BadgeShape.Circle;
            beepSimpleGrid1.BadgeText = "";
            beepSimpleGrid1.BlockID = null;
            beepSimpleGrid1.BorderColor = Color.Black;
            beepSimpleGrid1.BorderDashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
            beepSimpleGrid1.BorderRadius = 8;
            beepSimpleGrid1.BorderStyle = BorderStyle.FixedSingle;
            beepSimpleGrid1.BorderThickness = 1;
            beepSimpleGrid1.BottomoffsetForDrawingRect = 0;
            beepSimpleGrid1.BoundProperty = null;
            beepSimpleGrid1.CanBeFocused = true;
            beepSimpleGrid1.CanBeHovered = false;
            beepSimpleGrid1.CanBePressed = true;
            beepSimpleGrid1.Category = Utilities.DbFieldCategory.String;
            beepSimpleGrid1.ColumnHeaderHeight = 40;
            beepColumnConfig1.AggregationType = AggregationType.None;
            beepColumnConfig1.AllowSort = true;
            beepColumnConfig1.CellEditor = BeepColumnType.CheckBoxBool;
            beepColumnConfig1.ColumnCaption = "☑";
            beepColumnConfig1.ColumnName = "Sel";
            beepColumnConfig1.ColumnType = Utilities.DbFieldCategory.Boolean;
            beepColumnConfig1.CustomControlName = null;
            beepColumnConfig1.Date = new DateTime(0L);
            beepColumnConfig1.DecimalPlaces = 0;
            beepColumnConfig1.DefaultValue = null;
            beepColumnConfig1.EnumSourceType = null;
            beepColumnConfig1.Filter = null;
            beepColumnConfig1.Format = null;
            beepColumnConfig1.GuidID = "b12fa070-81a7-4605-b508-583bdddc26cc";
            beepColumnConfig1.HasTotal = false;
            beepColumnConfig1.ImagePath = null;
            beepColumnConfig1.Index = 0;
            beepColumnConfig1.IsAutoIncrement = false;
            beepColumnConfig1.IsFilteOn = false;
            beepColumnConfig1.IsFiltered = false;
            beepColumnConfig1.IsForeignKey = false;
            beepColumnConfig1.IsNullable = false;
            beepColumnConfig1.IsPrimaryKey = false;
            beepColumnConfig1.IsRequired = false;
            beepColumnConfig1.IsRowID = false;
            beepColumnConfig1.IsRowNumColumn = false;
            beepColumnConfig1.IsSelectionCheckBox = true;
            beepColumnConfig1.IsSorted = false;
            beepColumnConfig1.IsTotalOn = false;
            beepColumnConfig1.IsUnbound = true;
            beepColumnConfig1.IsUnique = false;
            beepColumnConfig1.MaxImageHeight = 32;
            beepColumnConfig1.MaxImageWidth = 32;
            beepColumnConfig1.MaxValue = 0;
            beepColumnConfig1.MinValue = 0;
            beepColumnConfig1.OldValue = new decimal(new int[] { 0, 0, 0, 0 });
            beepColumnConfig1.ParentColumnName = null;
            beepColumnConfig1.PropertyTypeName = "System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e";
            beepColumnConfig1.QueryToGetValues = null;
            beepColumnConfig1.ReadOnly = false;
            beepColumnConfig1.Resizable = DataGridViewTriState.False;
            beepColumnConfig1.ShowFilterIcon = true;
            beepColumnConfig1.ShowSortIcon = true;
            beepColumnConfig1.SortDirection = SortDirection.Ascending;
            beepColumnConfig1.SortMode = DataGridViewColumnSortMode.NotSortable;
            beepColumnConfig1.Sticked = true;
            beepColumnConfig1.Total = new decimal(new int[] { 0, 0, 0, 0 });
            beepColumnConfig1.Visible = false;
            beepColumnConfig1.Width = 30;
            beepColumnConfig2.AggregationType = AggregationType.Count;
            beepColumnConfig2.AllowSort = true;
            beepColumnConfig2.ColumnCaption = "#";
            beepColumnConfig2.ColumnName = "RowNum";
            beepColumnConfig2.ColumnType = Utilities.DbFieldCategory.Numeric;
            beepColumnConfig2.CustomControlName = null;
            beepColumnConfig2.Date = new DateTime(0L);
            beepColumnConfig2.DecimalPlaces = 0;
            beepColumnConfig2.DefaultValue = null;
            beepColumnConfig2.EnumSourceType = null;
            beepColumnConfig2.Filter = null;
            beepColumnConfig2.Format = null;
            beepColumnConfig2.GuidID = "4dc50bbf-a06f-4a22-ba10-bc0764c9010a";
            beepColumnConfig2.HasTotal = false;
            beepColumnConfig2.ImagePath = null;
            beepColumnConfig2.Index = 1;
            beepColumnConfig2.IsAutoIncrement = false;
            beepColumnConfig2.IsFilteOn = false;
            beepColumnConfig2.IsFiltered = false;
            beepColumnConfig2.IsForeignKey = false;
            beepColumnConfig2.IsNullable = false;
            beepColumnConfig2.IsPrimaryKey = false;
            beepColumnConfig2.IsRequired = false;
            beepColumnConfig2.IsRowID = false;
            beepColumnConfig2.IsRowNumColumn = true;
            beepColumnConfig2.IsSelectionCheckBox = false;
            beepColumnConfig2.IsSorted = false;
            beepColumnConfig2.IsTotalOn = false;
            beepColumnConfig2.IsUnbound = true;
            beepColumnConfig2.IsUnique = false;
            beepColumnConfig2.MaxImageHeight = 32;
            beepColumnConfig2.MaxImageWidth = 32;
            beepColumnConfig2.MaxValue = 0;
            beepColumnConfig2.MinValue = 0;
            beepColumnConfig2.OldValue = new decimal(new int[] { 0, 0, 0, 0 });
            beepColumnConfig2.ParentColumnName = null;
            beepColumnConfig2.PropertyTypeName = "System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e";
            beepColumnConfig2.QueryToGetValues = null;
            beepColumnConfig2.ReadOnly = false;
            beepColumnConfig2.Resizable = DataGridViewTriState.False;
            beepColumnConfig2.ShowFilterIcon = true;
            beepColumnConfig2.ShowSortIcon = true;
            beepColumnConfig2.SortDirection = SortDirection.Ascending;
            beepColumnConfig2.SortMode = DataGridViewColumnSortMode.NotSortable;
            beepColumnConfig2.Sticked = true;
            beepColumnConfig2.Total = new decimal(new int[] { 0, 0, 0, 0 });
            beepColumnConfig2.Width = 30;
            beepColumnConfig3.AggregationType = AggregationType.None;
            beepColumnConfig3.AllowSort = true;
            beepColumnConfig3.ColumnCaption = "RowID";
            beepColumnConfig3.ColumnName = "RowID";
            beepColumnConfig3.ColumnType = Utilities.DbFieldCategory.Numeric;
            beepColumnConfig3.CustomControlName = null;
            beepColumnConfig3.Date = new DateTime(0L);
            beepColumnConfig3.DecimalPlaces = 0;
            beepColumnConfig3.DefaultValue = null;
            beepColumnConfig3.EnumSourceType = null;
            beepColumnConfig3.Filter = null;
            beepColumnConfig3.Format = null;
            beepColumnConfig3.GuidID = "7b530351-b845-48f2-941d-8245afa83669";
            beepColumnConfig3.HasTotal = false;
            beepColumnConfig3.ImagePath = null;
            beepColumnConfig3.Index = 2;
            beepColumnConfig3.IsAutoIncrement = false;
            beepColumnConfig3.IsFilteOn = false;
            beepColumnConfig3.IsFiltered = false;
            beepColumnConfig3.IsForeignKey = false;
            beepColumnConfig3.IsNullable = false;
            beepColumnConfig3.IsPrimaryKey = false;
            beepColumnConfig3.IsRequired = false;
            beepColumnConfig3.IsRowID = true;
            beepColumnConfig3.IsRowNumColumn = false;
            beepColumnConfig3.IsSelectionCheckBox = false;
            beepColumnConfig3.IsSorted = false;
            beepColumnConfig3.IsTotalOn = false;
            beepColumnConfig3.IsUnbound = true;
            beepColumnConfig3.IsUnique = false;
            beepColumnConfig3.MaxImageHeight = 32;
            beepColumnConfig3.MaxImageWidth = 32;
            beepColumnConfig3.MaxValue = 0;
            beepColumnConfig3.MinValue = 0;
            beepColumnConfig3.OldValue = new decimal(new int[] { 0, 0, 0, 0 });
            beepColumnConfig3.ParentColumnName = null;
            beepColumnConfig3.PropertyTypeName = "System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e";
            beepColumnConfig3.QueryToGetValues = null;
            beepColumnConfig3.ReadOnly = false;
            beepColumnConfig3.Resizable = DataGridViewTriState.False;
            beepColumnConfig3.ShowFilterIcon = true;
            beepColumnConfig3.ShowSortIcon = true;
            beepColumnConfig3.SortDirection = SortDirection.Ascending;
            beepColumnConfig3.SortMode = DataGridViewColumnSortMode.NotSortable;
            beepColumnConfig3.Sticked = true;
            beepColumnConfig3.Total = new decimal(new int[] { 0, 0, 0, 0 });
            beepColumnConfig3.Visible = false;
            beepColumnConfig3.Width = 30;
            beepSimpleGrid1.Columns.Add(beepColumnConfig1);
            beepSimpleGrid1.Columns.Add(beepColumnConfig2);
            beepSimpleGrid1.Columns.Add(beepColumnConfig3);
            beepSimpleGrid1.ComponentName = "beepSimpleGrid1";
            beepSimpleGrid1.DataSource = null;
            beepSimpleGrid1.DataSourceProperty = null;
            beepSimpleGrid1.DisabledBackColor = Color.White;
            beepSimpleGrid1.DisabledBorderColor = Color.Empty;
            beepSimpleGrid1.DisabledForeColor = Color.Black;
            //beepSimpleGrid1.DisableDpiAndScaling = true;
            beepSimpleGrid1.Dock = DockStyle.Fill;
           // beepSimpleGrid1.DrawingRect = new Rectangle(0, 0, 1044, 738);
            beepSimpleGrid1.Easing = EasingType.Linear;
            beepSimpleGrid1.EnableHighQualityRendering = true;
            beepSimpleGrid1.EnableRippleEffect = false;
            beepSimpleGrid1.EnableSplashEffect = true;
            beepSimpleGrid1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepSimpleGrid1.FieldID = null;
            beepSimpleGrid1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepSimpleGrid1.FloatingLabel = string.Empty;
            beepSimpleGrid1.FocusBackColor = Color.White;
            beepSimpleGrid1.FocusBorderColor = Color.Gray;
            beepSimpleGrid1.FocusForeColor = Color.FromArgb(40, 40, 40);
            beepSimpleGrid1.FocusIndicatorColor = Color.Blue;
            beepSimpleGrid1.ForeColor = Color.FromArgb(40, 40, 40);
            beepSimpleGrid1.Form = null;
            beepSimpleGrid1.GlassmorphismBlur = 10F;
            beepSimpleGrid1.GlassmorphismOpacity = 0.1F;
            beepSimpleGrid1.GradientAngle = 0F;
            beepSimpleGrid1.GradientDirection = System.Drawing.Drawing2D.LinearGradientMode.Horizontal;
            beepSimpleGrid1.GradientEndColor = Color.Gray;
            beepSimpleGrid1.GradientStartColor = Color.Gray;
            beepSimpleGrid1.GridMode = false;
            beepSimpleGrid1.GuidID = "8f70e6e9-14bf-41e8-9d73-94248d65be2d";
            beepSimpleGrid1.HelperText = "";
            beepSimpleGrid1.HitAreaEventOn = false;
            beepSimpleGrid1.HitTestControl = null;
            beepSimpleGrid1.HoverBackColor = Color.White;
            beepSimpleGrid1.HoverBorderColor = Color.Gray;
            beepSimpleGrid1.HoveredBackcolor = Color.Wheat;
            beepSimpleGrid1.HoverForeColor = Color.FromArgb(40, 40, 40);
            beepSimpleGrid1.Id = -1;
            beepSimpleGrid1.InactiveBorderColor = Color.Gray;
            beepSimpleGrid1.IsAcceptButton = false;
            beepSimpleGrid1.IsBorderAffectedByTheme = true;
            beepSimpleGrid1.IsCancelButton = false;
            beepSimpleGrid1.IsChild = false;
            beepSimpleGrid1.IsCustomeBorder = false;
            beepSimpleGrid1.IsDefault = false;
            beepSimpleGrid1.IsDeleted = false;
            beepSimpleGrid1.IsDirty = false;
            beepSimpleGrid1.IsEditable = false;
            beepSimpleGrid1.IsFocused = false;
            beepSimpleGrid1.IsFrameless = false;
            beepSimpleGrid1.IsHovered = false;
            beepSimpleGrid1.IsNew = false;
            beepSimpleGrid1.IsPressed = false;
            beepSimpleGrid1.IsReadOnly = false;
            beepSimpleGrid1.IsRequired = false;
            beepSimpleGrid1.IsRounded = true;
            beepSimpleGrid1.IsRoundedAffectedByTheme = true;
            beepSimpleGrid1.IsSelected = false;
            beepSimpleGrid1.IsSelectedOptionOn = false;
            beepSimpleGrid1.IsShadowAffectedByTheme = true;
            beepSimpleGrid1.IsVisible = true;
            beepSimpleGrid1.Items = null;
            beepSimpleGrid1.LabelText = "";
            beepSimpleGrid1.LeftoffsetForDrawingRect = 0;
            beepSimpleGrid1.LinkedProperty = null;
            beepSimpleGrid1.Location = new Point(0, 0);            beepSimpleGrid1.MaxHitListDrawPerFrame = 0;
            beepSimpleGrid1.ModernGradientType = ModernGradientType.Subtle;
            beepSimpleGrid1.Name = "beepSimpleGrid1";
            beepSimpleGrid1.OverrideFontSize = TypeStyleFontSize.None;
            beepSimpleGrid1.ParentBackColor = Color.Empty;
            // beepSimpleGrid1.ParentControl = null;
            beepSimpleGrid1.PressedBackColor = Color.White;
            beepSimpleGrid1.PressedBorderColor = Color.Gray;
            beepSimpleGrid1.PressedForeColor = Color.Gray;
            beepSimpleGrid1.RadialCenter = (PointF)resources.GetObject("beepSimpleGrid1.RadialCenter");
            beepSimpleGrid1.ReadOnly = false;
            beepSimpleGrid1.RightoffsetForDrawingRect = 0;
            beepSimpleGrid1.RowHeight = 25;
            beepSimpleGrid1.SavedGuidID = null;
            beepSimpleGrid1.SavedID = null;
            beepSimpleGrid1.SelectedBackColor = Color.White;
            beepSimpleGrid1.SelectedBorderColor = Color.Empty;
            beepSimpleGrid1.SelectedForeColor = Color.FromArgb(40, 40, 40);
            beepSimpleGrid1.SelectedValue = null;
            beepSimpleGrid1.ShadowColor = Color.Black;
            beepSimpleGrid1.ShadowOffset = 0;
            beepSimpleGrid1.ShadowOpacity = 0.5F;
            beepSimpleGrid1.ShowAllBorders = false;
            beepSimpleGrid1.ShowBottomBorder = false;
            beepSimpleGrid1.ShowColumnHeaders = true;
            beepSimpleGrid1.ShowFocusIndicator = false;
            beepSimpleGrid1.ShowLeftBorder = false;
            beepSimpleGrid1.ShowNavigator = true;
            beepSimpleGrid1.ShowRightBorder = false;
            beepSimpleGrid1.ShowShadow = false;
            beepSimpleGrid1.ShowTopBorder = false;
            beepSimpleGrid1.Size = new Size(1044, 738);
            beepSimpleGrid1.SlideFrom = SlideDirection.Left;
            beepSimpleGrid1.StaticNotMoving = false;
            beepSimpleGrid1.TabIndex = 16;
          
            beepSimpleGrid1.TempBackColor = Color.Empty;
            beepSimpleGrid1.Text = "beepSimpleGrid1";
            beepSimpleGrid1.Theme = "DefaultType";
            beepSimpleGrid1.ToolTipText = "";
            beepSimpleGrid1.TopoffsetForDrawingRect = 0;
          
            beepSimpleGrid1.UseExternalBufferedGraphics = false;
            beepSimpleGrid1.UseGlassmorphism = false;
            beepSimpleGrid1.UseGradientBackground = false;
            beepSimpleGrid1.UseThemeFont = true;
            // 
            // uc_FilterForm
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            Name = "uc_FilterForm";
            Size = new Size(1044, 738);
            ResumeLayout(false);
        }

        #endregion
        private BeepLabel beepLabel1;
        private BeepTextBox beepTextBox1;
        private TheTechIdea.Beep.Winform.Controls.GridX.BeepGridPro beepSimpleGrid1;
    }
}
