namespace TheTechIdea.Beep.Winform.Default.Views
{
    partial class Form2
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            GraphicsPath graphicsPath1 = new GraphicsPath();
            GraphicsPath graphicsPath2 = new GraphicsPath();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form2));
            GraphicsPath graphicsPath3 = new GraphicsPath();
            GraphicsPath graphicsPath4 = new GraphicsPath();
            GraphicsPath graphicsPath5 = new GraphicsPath();
            GraphicsPath graphicsPath6 = new GraphicsPath();
            beepButton1 = new BeepButton();
            beepLabel1 = new BeepLabel();
            SuspendLayout();
            // 
            // beepButton1
            // 
            beepButton1.AnimationDuration = 500;
            beepButton1.AnimationType = DisplayAnimationType.None;
            beepButton1.ApplyThemeOnImage = false;
            beepButton1.ApplyThemeToChilds = true;
            beepButton1.AutoDrawHitListComponents = true;
            beepButton1.AutoSizeContent = false;
            beepButton1.BackColor = Color.FromArgb(232, 238, 248);
            beepButton1.BadgeBackColor = Color.Red;
            beepButton1.BadgeFont = new Font("Segoe UI", 7F, FontStyle.Bold);
            beepButton1.BadgeForeColor = Color.White;
            beepButton1.BadgeShape = BadgeShape.Circle;
            beepButton1.BlockID = null;
            beepButton1.BorderColor = Color.FromArgb(209, 213, 219);
            beepButton1.BorderDashStyle = DashStyle.Solid;
            beepButton1.BorderPainter = BeepControlStyle.Modern;
            graphicsPath1.FillMode = FillMode.Alternate;
            beepButton1.BorderPath = graphicsPath1;
            beepButton1.BorderRadius = 8;
            beepButton1.BorderRect = new Rectangle(1, 1, 97, 33);
            beepButton1.BorderStyle = BorderStyle.FixedSingle;
            beepButton1.BorderThickness = 2;
            beepButton1.BottomoffsetForDrawingRect = 0;
            beepButton1.BoundProperty = null;
            beepButton1.ButtonMinSize = new Size(32, 32);
            beepButton1.ButtonType = ButtonType.Normal;
            beepButton1.CanBeFocused = true;
            beepButton1.CanBeHovered = true;
            beepButton1.CanBePressed = true;
            beepButton1.CanBeSelected = true;
            beepButton1.Category = DbFieldCategory.Boolean;
            beepButton1.ComponentName = "BaseControl";
            beepButton1.ContentRect = new Rectangle(0, 0, 0, 0);
            graphicsPath2.FillMode = FillMode.Alternate;
            beepButton1.ContentShape = graphicsPath2;
            beepButton1.ControlStyle = BeepControlStyle.Modern;
            beepButton1.CustomIconColor = Color.Black;
            beepButton1.CustomIconPath = "";
            beepButton1.CustomIconPosition = Winform.Controls.Badges.BadgeAnchor.TopRight;
            beepButton1.CustomPadding = new Padding(0);
            beepButton1.DataContext = null;
            beepButton1.DataSourceProperty = null;
            beepButton1.DisabledBackColor = Color.FromArgb(244, 246, 252);
            beepButton1.DisabledBorderColor = Color.Gray;
            beepButton1.DisabledForeColor = Color.FromArgb(222, 223, 229);
            beepButton1.DrawingRect = new Rectangle(15, 15, 69, 5);
            beepButton1.Easing = EasingType.Linear;
            beepButton1.EnableHighQualityRendering = true;
            beepButton1.EnableRippleEffect = false;
            beepButton1.EnableSplashEffect = false;
            beepButton1.ErrorColor = Color.Empty;
            beepButton1.ErrorText = "";
            beepButton1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepButton1.FieldID = null;
            beepButton1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepButton1.FloatingLabel = "";
            beepButton1.FloatingLabelOn = false;
            beepButton1.FocusBackColor = Color.FromArgb(31, 95, 255);
            beepButton1.FocusBorderColor = Color.RoyalBlue;
            beepButton1.FocusForeColor = Color.FromArgb(255, 255, 255);
            beepButton1.FocusIndicatorColor = Color.RoyalBlue;
            beepButton1.ForeColor = Color.FromArgb(38, 44, 57);
            beepButton1.Form = null;
            beepButton1.GlassmorphismBlur = 10F;
            beepButton1.GlassmorphismOpacity = 0.1F;
            beepButton1.GradientAngle = 0F;
            beepButton1.GradientDirection = LinearGradientMode.Horizontal;
            beepButton1.GradientEndColor = Color.Gray;
            beepButton1.GradientStartColor = Color.LightGray;
            beepButton1.GridMode = false;
            beepButton1.GuidID = "49b96e63-9ee3-44e5-950f-32e539442ce6";
            beepButton1.HasError = false;
            beepButton1.HelperText = "";
            beepButton1.HelperTextOn = false;
            beepButton1.HideText = false;
            beepButton1.HitAreaEventOn = false;
            beepButton1.HitTestControl = null;
            beepButton1.HoverBackColor = Color.FromArgb(220, 229, 242);
            beepButton1.HoverBorderColor = Color.Blue;
            beepButton1.HoveredBackcolor = Color.FromArgb(220, 229, 242);
            beepButton1.HoverForeColor = Color.FromArgb(38, 44, 57);
            beepButton1.IconKey = "";
            beepButton1.IconSize = 20;
            beepButton1.Id = -1;
            beepButton1.Image = null;
            beepButton1.ImageAlign = ContentAlignment.MiddleLeft;
            beepButton1.ImageClicked = null;
            beepButton1.ImageEmbededin = ImageEmbededin.Button;
            beepButton1.ImagePath = "";
            beepButton1.InactiveBorderColor = Color.Gray;
            beepButton1.IndicatorLineColor = Color.Red;
            beepButton1.IndicatorLineStyle = IndicatorLineStyle.Solid;
            graphicsPath3.FillMode = FillMode.Alternate;
            beepButton1.InnerShape = graphicsPath3;
            beepButton1.IsAcceptButton = false;
            beepButton1.IsBorderAffectedByTheme = true;
            beepButton1.IsCancelButton = false;
            beepButton1.IsChild = false;
            beepButton1.IsColorFromTheme = true;
            beepButton1.IsCustomeBorder = false;
            beepButton1.IsDefault = false;
            beepButton1.IsDeleted = false;
            beepButton1.IsDirty = false;
            beepButton1.IsEditable = true;
            beepButton1.IsFocused = false;
            beepButton1.IsFrameless = false;
            beepButton1.IsHovered = false;
            beepButton1.IsNew = false;
            beepButton1.IsPopupOpen = false;
            beepButton1.IsPressed = false;
            beepButton1.IsReadOnly = false;
            beepButton1.IsRequired = false;
            beepButton1.IsRounded = true;
            beepButton1.IsRoundedAffectedByTheme = true;
            beepButton1.IsSelected = false;
            beepButton1.IsSelectedOptionOn = false;
            beepButton1.IsShadowAffectedByTheme = true;
            beepButton1.IsSideMenuChild = false;
            beepButton1.IsStillButton = false;
            beepButton1.IsTransparentBackground = false;
            beepButton1.IsValid = true;
            beepButton1.IsVisible = true;
            beepButton1.LabelPosition = LabelPosition.Left;
            beepButton1.LabelText = "";
            beepButton1.LabelTextOn = false;
            beepButton1.LeadingIconPath = "";
            beepButton1.LeadingImagePath = "";
            beepButton1.LeftoffsetForDrawingRect = 0;
            beepButton1.LinkedProperty = null;
            beepButton1.Location = new Point(220, 141);
            beepButton1.Margin = new Padding(0);
            beepButton1.MaxHitListDrawPerFrame = 0;
            beepButton1.MaxImageSize = new Size(16, 16);
            beepButton1.ModernGradientType = ModernGradientType.None;
            beepButton1.Name = "beepButton1";
            beepButton1.OuterShape = null;
            beepButton1.OverrideFontSize = TypeStyleFontSize.None;
            beepButton1.PainterKind = BaseControlPainterKind.Classic;
            beepButton1.ParentBackColor = Color.Empty;
            beepButton1.ParentControl = null;
            beepButton1.PopPosition = BeepPopupFormPosition.Bottom;
            beepButton1.PopupListForm = null;
            beepButton1.PopupMode = false;
            beepButton1.PressedBackColor = Color.FromArgb(205, 218, 236);
            beepButton1.PressedBorderColor = Color.DarkGray;
            beepButton1.PressedForeColor = Color.FromArgb(38, 44, 57);
            beepButton1.RadialCenter = (PointF)resources.GetObject("beepButton1.RadialCenter");
            beepButton1.RightoffsetForDrawingRect = 0;
            beepButton1.SavedGuidID = null;
            beepButton1.SavedID = null;
            beepButton1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepButton1.SelectedBackColor = Color.FromArgb(31, 95, 255);
            beepButton1.SelectedBorderColor = Color.Green;
            beepButton1.SelectedForeColor = Color.FromArgb(255, 255, 255);
            beepButton1.SelectedIndex = 0;
            beepButton1.SelectedItem = null;
            beepButton1.SelectedValue = null;
            beepButton1.ShadowColor = Color.Black;
            beepButton1.ShadowOffset = 3;
            beepButton1.ShadowOpacity = 0.25F;
            beepButton1.ShowAllBorders = false;
            beepButton1.ShowBottomBorder = false;
            beepButton1.ShowFocusIndicator = false;
            beepButton1.ShowIndicatorLine = false;
            beepButton1.ShowLabelAboveBorder = false;
            beepButton1.ShowLeftBorder = false;
            beepButton1.ShowRightBorder = false;
            beepButton1.ShowShadow = false;
            beepButton1.ShowTopBorder = false;
            beepButton1.Size = new Size(100, 36);
            beepButton1.SlideFrom = SlideDirection.Left;
            beepButton1.SplashColor = Color.Empty;
            beepButton1.StaticNotMoving = false;
            beepButton1.TabIndex = 0;
            beepButton1.TempBackColor = Color.LightGray;
            beepButton1.Text = "beepButton1";
            beepButton1.TextAlign = ContentAlignment.MiddleCenter;
            beepButton1.TextFont = new Font("Segoe UI", 10F);
            beepButton1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepButton1.Theme = "ModernTheme";
            beepButton1.TooltipFont = null;
            beepButton1.TooltipMaxSize = null;
            beepButton1.ToolTipText = "";
            beepButton1.TopoffsetForDrawingRect = 0;
            beepButton1.TrailingIconPath = "";
            beepButton1.TrailingImagePath = "";
            beepButton1.UseExternalBufferedGraphics = true;
            beepButton1.UseFormStylePaint = true;
            beepButton1.UseGlassmorphism = false;
            beepButton1.UseGradientBackground = false;
            beepButton1.UseScaledFont = false;
            beepButton1.UseThemeFont = true;
            beepButton1.ValidationIcon = Winform.Controls.Badges.ValidationState.None;
            beepButton1.ValidationIconPosition = Winform.Controls.Badges.BadgeAnchor.TopRight;
            // 
            // beepLabel1
            // 
            beepLabel1.AccessibleDescription = "beepLabel1";
            beepLabel1.AccessibleName = "beepLabel1";
            beepLabel1.AccessibleRole = AccessibleRole.StaticText;
            beepLabel1.AnimationDuration = 500;
            beepLabel1.AnimationType = DisplayAnimationType.None;
            beepLabel1.ApplyThemeOnImage = false;
            beepLabel1.ApplyThemeToChilds = true;
            beepLabel1.AutoDrawHitListComponents = true;
            beepLabel1.BackColor = Color.FromArgb(255, 255, 255);
            beepLabel1.BadgeBackColor = Color.Red;
            beepLabel1.BadgeFont = new Font("Segoe UI", 7F, FontStyle.Bold);
            beepLabel1.BadgeForeColor = Color.White;
            beepLabel1.BadgeShape = BadgeShape.Circle;
            beepLabel1.BlockID = null;
            beepLabel1.BorderColor = Color.FromArgb(209, 213, 219);
            beepLabel1.BorderDashStyle = DashStyle.Solid;
            beepLabel1.BorderPainter = BeepControlStyle.Modern;
            graphicsPath4.FillMode = FillMode.Alternate;
            beepLabel1.BorderPath = graphicsPath4;
            beepLabel1.BorderRadius = 8;
            beepLabel1.BorderRect = new Rectangle(1, 1, 197, 25);
            beepLabel1.BorderStyle = BorderStyle.FixedSingle;
            beepLabel1.BorderThickness = 2;
            beepLabel1.BottomoffsetForDrawingRect = 0;
            beepLabel1.BoundProperty = "Text";
            beepLabel1.CanBeFocused = false;
            beepLabel1.CanBeHovered = true;
            beepLabel1.CanBePressed = true;
            beepLabel1.CanBeSelected = true;
            beepLabel1.Category = DbFieldCategory.String;
            beepLabel1.ColorProfile.BackColor = Color.Empty;
            beepLabel1.ColorProfile.BorderColor = Color.Empty;
            beepLabel1.ColorProfile.DisabledBackColor = Color.Empty;
            beepLabel1.ColorProfile.DisabledForeColor = Color.Empty;
            beepLabel1.ColorProfile.ForeColor = Color.Empty;
            beepLabel1.ColorProfile.SubHeaderForeColor = Color.Empty;
            beepLabel1.ComponentName = "BaseControl";
            beepLabel1.ContentRect = new Rectangle(0, 0, 0, 0);
            graphicsPath5.FillMode = FillMode.Alternate;
            beepLabel1.ContentShape = graphicsPath5;
            beepLabel1.ControlStyle = BeepControlStyle.Modern;
            beepLabel1.CustomIconColor = Color.Black;
            beepLabel1.CustomIconPath = "";
            beepLabel1.CustomIconPosition = Winform.Controls.Badges.BadgeAnchor.TopRight;
            beepLabel1.CustomPadding = new Padding(0);
            beepLabel1.DataContext = null;
            beepLabel1.DataSourceProperty = null;
            beepLabel1.DisabledBackColor = Color.FromArgb(244, 246, 252);
            beepLabel1.DisabledBorderColor = Color.Gray;
            beepLabel1.DisabledForeColor = Color.FromArgb(222, 223, 229);
            beepLabel1.DrawingRect = new Rectangle(1, 1, 197, 25);
            beepLabel1.Easing = EasingType.Linear;
            beepLabel1.EnableHighQualityRendering = true;
            beepLabel1.EnableRippleEffect = false;
            beepLabel1.EnableSplashEffect = false;
            beepLabel1.ErrorColor = Color.Empty;
            beepLabel1.ErrorText = "";
            beepLabel1.ExternalDrawingLayer = DrawingLayer.AfterAll;
            beepLabel1.FieldID = null;
            beepLabel1.FilledBackgroundColor = Color.FromArgb(20, 0, 0, 0);
            beepLabel1.FloatingLabel = "";
            beepLabel1.FloatingLabelOn = false;
            beepLabel1.FocusBackColor = Color.LightYellow;
            beepLabel1.FocusBorderColor = Color.RoyalBlue;
            beepLabel1.FocusForeColor = Color.Black;
            beepLabel1.FocusIndicatorColor = Color.RoyalBlue;
            beepLabel1.ForeColor = Color.FromArgb(38, 44, 57);
            beepLabel1.Form = null;
            beepLabel1.GlassmorphismBlur = 10F;
            beepLabel1.GlassmorphismOpacity = 0.1F;
            beepLabel1.GradientAngle = 0F;
            beepLabel1.GradientDirection = LinearGradientMode.Horizontal;
            beepLabel1.GradientEndColor = Color.Gray;
            beepLabel1.GradientStartColor = Color.LightGray;
            beepLabel1.GridMode = false;
            beepLabel1.GuidID = "99f15023-5a3b-4b1c-94e6-516125af2ad9";
            beepLabel1.HasError = false;
            beepLabel1.HeaderSubheaderSpacing = 2;
            beepLabel1.HelperText = "";
            beepLabel1.HelperTextOn = false;
            beepLabel1.HideText = false;
            beepLabel1.HitAreaEventOn = false;
            beepLabel1.HitTestControl = null;
            beepLabel1.HoverBackColor = Color.FromArgb(251, 252, 255);
            beepLabel1.HoverBorderColor = Color.Blue;
            beepLabel1.HoveredBackcolor = Color.FromArgb(251, 252, 255);
            beepLabel1.HoverForeColor = Color.FromArgb(38, 44, 57);
            beepLabel1.IconKey = "";
            beepLabel1.IconSize = 20;
            beepLabel1.Id = -1;
            beepLabel1.ImageAlign = ContentAlignment.MiddleLeft;
            beepLabel1.ImagePath = "";
            beepLabel1.InactiveBorderColor = Color.Gray;
            beepLabel1.IndicatorLineColor = Color.Red;
            beepLabel1.IndicatorLineStyle = IndicatorLineStyle.Solid;
            graphicsPath6.FillMode = FillMode.Alternate;
            beepLabel1.InnerShape = graphicsPath6;
            beepLabel1.IsAcceptButton = false;
            beepLabel1.IsBorderAffectedByTheme = true;
            beepLabel1.IsCancelButton = false;
            beepLabel1.IsChild = true;
            beepLabel1.IsCustomeBorder = false;
            beepLabel1.IsDefault = false;
            beepLabel1.IsDeleted = false;
            beepLabel1.IsDirty = false;
            beepLabel1.IsEditable = true;
            beepLabel1.IsFocused = false;
            beepLabel1.IsFrameless = false;
            beepLabel1.IsHovered = false;
            beepLabel1.IsNew = false;
            beepLabel1.IsPressed = false;
            beepLabel1.IsReadOnly = false;
            beepLabel1.IsRequired = false;
            beepLabel1.IsRounded = true;
            beepLabel1.IsRoundedAffectedByTheme = true;
            beepLabel1.IsSelected = false;
            beepLabel1.IsSelectedOptionOn = false;
            beepLabel1.IsShadowAffectedByTheme = true;
            beepLabel1.IsTransparentBackground = false;
            beepLabel1.IsValid = true;
            beepLabel1.IsVisible = true;
            beepLabel1.LabelBackColor = Color.Empty;
            beepLabel1.LabelPosition = LabelPosition.Left;
            beepLabel1.LabelText = "";
            beepLabel1.LabelTextOn = false;
            beepLabel1.LeadingIconPath = "";
            beepLabel1.LeadingImagePath = "";
            beepLabel1.LeftoffsetForDrawingRect = 0;
            beepLabel1.LinkedProperty = null;
            beepLabel1.Location = new Point(45, 320);
            beepLabel1.Margin = new Padding(0);
            beepLabel1.MaxHitListDrawPerFrame = 0;
            beepLabel1.MaxImageSize = new Size(16, 16);
            beepLabel1.MinimumSize = new Size(88, 28);
            beepLabel1.ModernGradientType = ModernGradientType.None;
            beepLabel1.Multiline = false;
            beepLabel1.Name = "beepLabel1";
            beepLabel1.OuterShape = null;
            beepLabel1.OverrideFontSize = TypeStyleFontSize.None;
            beepLabel1.Padding = new Padding(1);
            beepLabel1.PainterKind = BaseControlPainterKind.Classic;
            beepLabel1.ParentBackColor = Color.FromArgb(255, 255, 255);
            beepLabel1.ParentControl = null;
            beepLabel1.PressedBackColor = Color.Gray;
            beepLabel1.PressedBorderColor = Color.DarkGray;
            beepLabel1.PressedForeColor = Color.White;
            beepLabel1.RadialCenter = (PointF)resources.GetObject("beepLabel1.RadialCenter");
            beepLabel1.RightoffsetForDrawingRect = 0;
            beepLabel1.SavedGuidID = null;
            beepLabel1.SavedID = null;
            beepLabel1.ScaleMode = ImageScaleMode.KeepAspectRatio;
            beepLabel1.SelectedBackColor = Color.FromArgb(92, 139, 255);
            beepLabel1.SelectedBorderColor = Color.Green;
            beepLabel1.SelectedForeColor = Color.FromArgb(58, 58, 58);
            beepLabel1.SelectedValue = null;
            beepLabel1.ShadowColor = Color.Black;
            beepLabel1.ShadowOffset = 3;
            beepLabel1.ShadowOpacity = 0.25F;
            beepLabel1.ShowAllBorders = false;
            beepLabel1.ShowBottomBorder = false;
            beepLabel1.ShowFocusIndicator = false;
            beepLabel1.ShowIndicatorLine = false;
            beepLabel1.ShowLabelAboveBorder = false;
            beepLabel1.ShowLeftBorder = false;
            beepLabel1.ShowRightBorder = false;
            beepLabel1.ShowShadow = false;
            beepLabel1.ShowTopBorder = false;
            beepLabel1.Size = new Size(200, 28);
            beepLabel1.SlideFrom = SlideDirection.Left;
            beepLabel1.StaticNotMoving = false;
            beepLabel1.StyleProfile.AutoEllipsis = false;
            beepLabel1.StyleProfile.HeaderSubheaderSpacing = 2;
            beepLabel1.StyleProfile.ImageAlign = ContentAlignment.MiddleLeft;
            beepLabel1.StyleProfile.Multiline = false;
            beepLabel1.StyleProfile.TextAlign = ContentAlignment.MiddleLeft;
            beepLabel1.StyleProfile.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepLabel1.StyleProfile.WordWrap = false;
            beepLabel1.SubHeaderFont = new Font("Segoe UI", 8F);
            beepLabel1.SubHeaderForeColor = Color.FromArgb(88, 94, 107);
            beepLabel1.SubHeaderText = "";
            beepLabel1.TabIndex = 2;
            beepLabel1.TempBackColor = Color.LightGray;
            beepLabel1.Text = "beepLabel1";
            beepLabel1.TextAlign = ContentAlignment.MiddleLeft;
            beepLabel1.TextFont = new Font("Segoe UI", 8F);
            beepLabel1.TextImageRelation = TextImageRelation.ImageBeforeText;
            beepLabel1.Theme = "ModernTheme";
            beepLabel1.TooltipFont = null;
            beepLabel1.TooltipMaxSize = null;
            beepLabel1.ToolTipText = "";
            beepLabel1.TopoffsetForDrawingRect = 0;
            beepLabel1.TrailingIconPath = "";
            beepLabel1.TrailingImagePath = "";
            beepLabel1.UseExternalBufferedGraphics = true;
            beepLabel1.UseFormStylePaint = true;
            beepLabel1.UseGlassmorphism = false;
            beepLabel1.UseGradientBackground = false;
            beepLabel1.UseScaledFont = false;
            beepLabel1.UseThemeFont = true;
            beepLabel1.ValidationIcon = Winform.Controls.Badges.ValidationState.None;
            beepLabel1.ValidationIconPosition = Winform.Controls.Badges.BadgeAnchor.TopRight;
            // 
            // Form2
            // 
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(800, 450);
            Controls.Add(beepLabel1);
            Controls.Add(beepButton1);
            Name = "Form2";
            Text = "Form2";
            ResumeLayout(false);
        }

        #endregion

        private BeepButton beepButton1;
        private BeepLabel beepLabel1;
    }
}